[package]
name = "smol"
version = "0.1.0"
authors = ["Hurshal Patel <hurshal@imap.cc>"]
edition = "2018"

[dependencies]
exitcode = "1.1.2"
termcolor = "1"
websocket = "0.22.3"
futures = "0.1.25"
tokio = "0.1.16"
pest = "2.1.0"
pest_derive = "2.1.0"

[dev-dependencies]
pretty_assertions = "0.6.1"
